# Generated by Django 2.2 on 2021-06-17 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wall_Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('user_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='app_wall.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_to_Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_to_Msg', models.CharField(max_length=255)),
                ('user_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='app_wall.User')),
                ('wall_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_to_message', to='app_wall.Wall_Msg')),
            ],
        ),
    ]
