# Generated by Django 2.2 on 2021-06-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_wall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall_msg',
            name='user_poster',
        ),
        migrations.DeleteModel(
            name='Comment_to_Msg',
        ),
        migrations.DeleteModel(
            name='Wall_Msg',
        ),
    ]
