# Generated by Django 2.2 on 2021-06-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_wall', '0002_auto_20210618_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
